name: comete
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "7176:7176"
    container_name: comete-back
  # front:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   container_name: comete-front
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: comete
      MYSQL_DATABASE: comete
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: comete
    ports:
      - "8080:80"
    depends_on:
      - mysql